-- Quick Tour Reviews Setup (Essential Reviews Only)
-- Run this in your Supabase SQL Editor

-- Create the tour_reviews table
CREATE TABLE IF NOT EXISTS tour_reviews (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tour_slug VARCHAR(255) NOT NULL,
    language VARCHAR(5) NOT NULL DEFAULT 'en',
    author VARCHAR(255) NOT NULL,
    author_location VARCHAR(255),
    rating INTEGER CHECK (rating >= 1 AND rating <= 5) DEFAULT 5,
    review_date DATE NOT NULL DEFAULT CURRENT_DATE,
    title VARCHAR(500) NOT NULL,
    content TEXT NOT NULL,
    verified BOOLEAN DEFAULT true,
    experience_type VARCHAR(100),
    helpful_count INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_tour_reviews_slug ON tour_reviews(tour_slug);
CREATE INDEX IF NOT EXISTS idx_tour_reviews_language ON tour_reviews(language);
CREATE INDEX IF NOT EXISTS idx_tour_reviews_rating ON tour_reviews(rating);

-- Insert sample reviews for key tours
INSERT INTO tour_reviews (tour_slug, language, author, author_location, rating, review_date, title, content, verified, experience_type) VALUES
('boulders-beach-penguin-colony', 'en', 'Sarah Johnson', 'London, UK', 5, '2024-01-15', 'Magical Penguin Encounter - A Family Adventure to Remember', 'Our family trip to Boulders Beach was absolutely magical! As a mother of two young children, I was concerned about finding activities that would captivate both my 8-year-old and 12-year-old, but the African penguins delivered beyond expectations. The moment we stepped onto the wooden boardwalk, we were transported into a wildlife wonderland where over 3,000 endangered African penguins have made their home since 1982. The well-designed boardwalk system ensures you are just meters away from these incredible jackass penguins - named for their distinctive braying calls that had my kids giggling throughout our visit. What impressed me most was the conservation story behind this colony. Learning that it all started with just two breeding pairs in 1982 and has grown to become one of the worlds most successful penguin conservation sites made this more than just a tourist attraction - it became an educational experience. The timing of our January visit could not have been better, coinciding with breeding season when penguin activity peaks. We witnessed incredible behaviors: penguins preening each other, feeding their fluffy gray chicks, and the adorable waddle-walks across the beach. For families seeking an authentic South African wildlife experience, Boulders Beach Penguin Colony is absolutely unmissable.', true, 'Family Adventure'),

('aquila-safari-tour', 'en', 'Michael Thompson', 'Edinburgh, Scotland', 5, '2024-01-18', 'Big Five Safari Excellence - Malaria-Free Wildlife Adventure from Cape Town', 'Our family day trip to Aquila Private Game Reserve exceeded every expectation for what a Big Five safari experience could deliver. As parents of three children aged 8, 12, and 16, we needed an adventure that would captivate teenagers while remaining safe and educational for younger family members. This 10,000-hectare conservancy, just two hours from Cape Town, provided the perfect solution with its malaria-free environment and guaranteed wildlife encounters. The morning began with a scenic drive through the stunning Karoo landscape, where our professional guide shared fascinating insights about South African geography and conservation efforts. Our 4x4 game drive delivered on every promise: all Big Five animals (lion, elephant, buffalo, leopard, and rhino) within the first hour, plus incredible encounters with giraffes, hippos, meerkats, and over 170 bird species. The professional rangers knowledge was extraordinary, providing educational context that transformed simple wildlife viewing into comprehensive lessons about African ecosystems. What distinguished this experience was the balance of excitement and education. Our children learned about anti-poaching efforts, renewable energy initiatives powering the reserve, and complex relationships between predators and prey in controlled conservation environments. For families seeking authentic Big Five safari experiences without malaria concerns, Aquila delivers world-class wildlife encounters while supporting crucial conservation efforts.', true, 'Family Safari'),

('shark-cage-diving-gansbaai', 'en', 'Marcus Rodriguez', 'Sydney, Australia', 5, '2024-01-16', 'Ultimate Adrenaline Experience - Face-to-Face with Great White Sharks', 'Shark cage diving in Gansbaai delivered the most intense wildlife encounter of my life, combining heart-pounding adrenaline with incredible marine conservation education. As someone who actively seeks extreme adventure experiences worldwide, this Great White shark encounter exceeded all expectations for safety, professionalism, and sheer excitement. The 2-hour boat journey from Gansbaai harbor provided perfect preparation time, with marine biologists sharing fascinating information about Great White shark behavior, migration patterns, and the crucial role these apex predators play in marine ecosystem balance. The moment of entering the cage - suspended in dark Atlantic waters while 4-meter Great White sharks glided past just centimeters away - created the most powerful connection with nature I have ever experienced. The sharks grace, power, and intelligence became immediately apparent, completely dispelling Hollywood-created fears and replacing them with profound respect for these magnificent creatures. The professional crew exceeded all safety expectations, with comprehensive equipment checks, detailed safety briefings, and constant monitoring that allowed complete focus on the incredible wildlife experience. For adventure seekers looking for authentic wildlife experiences that combine extreme excitement with conservation education, Gansbaai shark cage diving delivers unparalleled encounters with one of natures most misunderstood apex predators.', true, 'Extreme Wildlife'),

('cape-town-paragliding', 'en', 'Sofia Martinez', 'Barcelona, Spain', 5, '2024-01-25', 'Breathtaking Aerial Adventure - Paragliding Over Cape Town with Table Mountain Views', 'Cape Town paragliding delivered the most spectacular aerial experience imaginable, combining extreme sport thrills with breathtaking natural beauty that creates unforgettable memories and unique perspectives on one of the worlds most beautiful cities. As someone who has paraglided in the Alps, Andes, and Himalayas, I can confidently say Cape Town offers unparalleled scenic beauty and professional instruction that ranks among global paragliding destinations. The tandem flight experience with certified instructors provided perfect introduction to paragliding while ensuring complete safety confidence. The take-off from Signal Hill created immediate excitement as Cape Towns beauty revealed itself from aerial perspectives impossible to achieve otherwise. Soaring over the Atlantic coastline with Table Mountain, Robben Island, and the Cape Peninsula spread below created visual experiences that photography cannot adequately capture. The flight dynamics provided incredible sensations of freedom and connection with natural elements. Thermal currents and wind patterns created smooth, extended flight times that allowed comprehensive exploration of Cape Towns geography from birds-eye perspectives. What sets Cape Town paragliding apart from other destinations is the unique combination of urban, mountain, and coastal scenery visible during single flights. For adventure seekers, photography enthusiasts, or anyone wanting unique Cape Town experiences, paragliding delivers unparalleled aerial perspectives that create lasting memories.', true, 'Aerial Adventure'),

('tokara-wine-estate', 'en', 'Alexandre Dubois', 'Bordeaux, France', 5, '2024-02-05', 'Exceptional Winemaking - Stellenbosch Terroir with Michelin-Standard Cuisine', 'As a sommelier from Bordeaux with extensive experience in global wine regions, Tokara Wine Estate represents exceptional South African winemaking that rivals Frances finest appellations while offering unique Stellenbosch terroir characteristics impossible to replicate elsewhere. The estates position on the slopes of the Simonsberg mountain creates optimal growing conditions for premium varietals, with Mediterranean climate influences and ancient granite soils producing wines of extraordinary complexity and elegance. The wine tasting experience demonstrated remarkable sophistication in both viticulture and hospitality. The flagship Tokara Red blend showcased masterful winemaking technique with Bordeaux-style grape combinations that expressed distinctly South African terroir through mineral complexity and fruit concentration. The Sauvignon Blanc displayed exceptional cool-climate characteristics with tropical fruit aromatics balanced by crisp acidity that demonstrate Stellenboschs potential for world-class white wine production. The restaurant exceeded expectations with contemporary South African cuisine that perfectly complemented estate wines while showcasing local ingredients and culinary traditions. For wine enthusiasts seeking world-class tasting experiences with authentic terroir expression, Tokara Wine Estate delivers exceptional value and sophistication that validates South African wines position among global premium destinations.', true, 'Wine Tasting');

-- Enable Row Level Security
ALTER TABLE tour_reviews ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows all operations
CREATE POLICY "Enable all operations for all users" ON tour_reviews
    FOR ALL USING (true);

-- Grant permissions
GRANT ALL ON tour_reviews TO authenticated;
GRANT ALL ON tour_reviews TO anon;